# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZdC-dBJbxYlJZ364Y00avCkBqZwYoeE
"""

a=int(input("Enter price of first item: "))
b=int(input("Enter price of second item: "))
c=int(input("Enter price of third item: "))
t=a+b+c

if(t>50):
  t=t-(0.1*t)
  print(f"Total cost after 10% discount: {t}")
else:
  print(f"Total cost: {t}")